apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: threepilar-frontend
    openshift.io/log-alerting: 'true'
  name: threepilar-uwl-frontend
  namespace: ns2-uwl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threepilar-frontend
  template:
    metadata:
      labels:
        app: threepilar-frontend
    spec:
      containers:
      - image: quay.io/rhn_support_nigsmith/testapp-threepilars-frontend:latest
        imagePullPolicy: IfNotPresent
        name: threepilar-frontend
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.opentelemetry.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "threepilar-frontend"
        - name: BACKEND_URL
          value: "http://threepilar-backend-service:8091"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: threepilar-backend
    openshift.io/log-alerting: 'true'
  name: threepilar-uwl-backend
  namespace: ns2-uwl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threepilar-backend
  template:
    metadata:
      labels:
        app: threepilar-backend
    spec:
      containers:
      - image: quay.io/rhn_support_nigsmith/testapp-threepilars-backend:latest
        imagePullPolicy: IfNotPresent
        name: threepilar-backend
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.opentelemetry.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "threepilar-backend"
