apiVersion: v1
kind: Service
metadata:
  labels:
    app: threepilar-frontend
  name: threepilar-frontend-service
  namespace: ns2-uwl
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
    name: web
  selector:
    app: threepilar-frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: threepilar-backend
  name: threepilar-backend-service
  namespace: ns2-uwl
spec:
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
    name: web
  selector:
    app: threepilar-backend
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: threepilar-frontend-route
  namespace: ns2-uwl
spec:
  path: "/ping"
  to:
    kind: Service
    name: threepilar-frontend-service
    weight: 100
  port:
    targetPort: 8090
