apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: threepilar-frontend
  name: threepilar-frontend-monitor
  namespace: ns2-uwl
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: threepilar-frontend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: threepilar-backend
  name: threepilar-backend-monitor
  namespace: ns2-uwl
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: threepilar-backend
